### ISSUE TITLE
Problème à la création d'un serveur

### ISSUE THREAD

**Issue by Finch29** [MrDarkSkil/Launcher_Multigaming#16]
Salut, au moment de créer le serveur, aucune données ne s'inscrivent dans le BDD ... Je n'ai aucune erreurs dans les logs ! Des idées ? ;)
 Merci

**Comment by bozoweed** [comment]
euh j'ai eu le même bug j'ai donc demander a un amis de le créer depuits sont pc et ça a marcher

**Comment by MrDarkSkil** [comment]
Peut tu me donner les logs javascript ?

**Comment by bozoweed** [comment]
les logs sont clean c'est ça aussi qui est bizzar

**Comment by FlashModz** [comment]
Yop, dit moi c'est vide à quel moment ? après la mise en place du Web ?
hésite pas à m'ajouter sur Steam ou à nous rejoindre sur le discord et on vois sa ensemble :)

**Comment by MrDarkSkil** [comment]
Ton problème est toujours d'actualité ?
