### ISSUE TITLE
source of GameQ please

### ISSUE THREAD

**Issue by bozoweed** [MrDarkSkil/Launcher_Multigaming#17]
hi i will try to add reign of kings to the launcher but i don't have the protocol for ping the server so i will ask you the source of gameQ for i can try to add it
thanks
french = salut j'essaye d'ajouter reign of king au launcher mais je n'ai pas les protocol pour ping le server donc je te demande le site source de gameQ pour que je puisse essayer de l'ajouter 
merci

**Comment by FlashModz** [comment]
GameQ3 est bien plus complet :)

**Comment by bozoweed** [comment]
je vois pas mal merci :) si quelqu’un a déjà fait le protocole pour reign of king ça me conviendrais bien :)

**Comment by FlashModz** [comment]
No, i'm found the suject for you :)

Good Read :  https://reign-of-kings.net/help/api/

**Comment by MrDarkSkil** [comment]
EN: If you need help for add reign of king to the launcher tell me 😄 

FR: Si tu as besoin d'aide pour ajouter reign of king sur le launcher dit le moi 😄

**Comment by bozoweed** [comment]
très franchement je veut bien de l'aide car vue la montagne de code a démêler ça l'aide du créateur de base c'est très long et hasardeux :)

ps : j'ai fixer les système qui dit si le serv est online ou pas sur le site et le luncher c'était tous bêtes et j'ai rajouter le champ uid en steam64 sur le luncher ce qui permet de feinter ton problème pour trouver l'id steam et j'ai aussi eu un bug sur un de mes joueur qui avais déplacer sont dossier arma donc la key regedit retraits fausser pour patcher ça j'ai simplement ajouter la fonction check directory arma dans le bouton jouer ce qui dira au joueur si tous va bien ou non et vue que on lance arma3 avec arma3battleye.exe c'est aussi ce fichier que je vérifie par le luncher

**Comment by MrDarkSkil** [comment]
Nice !
Bah n’hésite pas à faire une pull request pour nous partager tous ça 😃

Et si tu veux, je suis disponible tout les soir sur discord https://discord.gg/uhbQBG9

**Comment by bozoweed** [comment]
nice pas de soucis je viens sur discord merci a toi :)
