### ISSUE TITLE
How to use this launcher for arma 3 ?

### ISSUE THREAD

**Issue by SvyatoyRus** [MrDarkSkil/Launcher_Multigaming#24]
There are instructions for installing the launcher for Arma 3 with addons?

**Comment by MrDarkSkil** [comment]
I work on 👍

**Comment by MrDarkSkil** [comment]
You can edit the launcher from Visual Studio and Program.cs file.
You need to change,

```
/* GENERAL OPTIONS */

string serverName = "Regalian"; /* Your serverName /
string apiUrl = "http://yourserver.com/"; / Link to API launcher Arma 3 */
```

**Comment by policeman18** [comment]
And A doubt, why the launcher give me a 404 error


-Sorry for the inconvenience

- Thanks

**Comment by MrDarkSkil** [comment]
Ok now you need to compile your launcher and upload it in /games/launcher/launcher.exe

**Comment by MrDarkSkil** [comment]
So, any news ?

**Comment by policeman18** [comment]
I compile my launcher, but when I open it gives me an error ( 404 Unable to connect to server )

And in the general options I have in the "Ip" the local ( 127.0.0.1 ).    I have this on windows ( Xammp )

-Thanks for reply @MrDarkSkil

**Comment by MrDarkSkil** [comment]
Do you have create the "launcher" directory and upload your launcher in this directory ?

**Comment by policeman18** [comment]
No, I open the launcher in the file " Debug "

**Comment by policeman18** [comment]
I create in local disk C folder named "games" - on this file I create other file named launcher but I have to move the launcher.exe in this folder?

Becouse I move on this file and the launcher don't open

**Comment by MrDarkSkil** [comment]
Why do you make that ? x)
For start the launcher he need all .dll in the debug folder, so if you want to start him on another folder, you need to copy all .exe and .dll.

For fix the 404 error you need to create a folder named "launcher" in your games folder (WEBPANEL) 
example: /var/www/html/games/launcher.

When you have create the launcher folder, upload your launcher.exe in this folder.
Example: /var/www/html/games/launcher/launcher.exe

**Comment by policeman18** [comment]
Thanks for reply!, but I put the launcher in html/games/launcher/launcher.exe ... And the launcher says a 404 error https://gyazo.com/36b09e55e1a154c6310d6d8aef1d139d

**Comment by policeman18** [comment]
What I do wrong? @MrDarkSkil

**Comment by policeman18** [comment]
I'm installing this in windows with xamp

**Comment by MrDarkSkil** [comment]
Add "/" on your apiUrl.

Example: http://my-ip.com/

**Comment by MrDarkSkil** [comment]
Do you have an IP of your webPanel ? 
If yes can you tel me that ?

**Comment by policeman18** [comment]
I have the webpanel in local, but I can't install the webpanel well becouse when I'm installing I can't create the Admin User ( I have to add my user in phpmyadmin )

**Comment by policeman18** [comment]
And now in the panel I can't upload the .exe of the launcher. Says me "File size exceeds limit."

**Comment by policeman18** [comment]
https://gyazo.com/e126cbb6d534f71fa1be3bed5debf3a2

**Comment by MrDarkSkil** [comment]
Upload manually the launcher, for upload on web panel you need to configure PHP

**Comment by policeman18** [comment]
Okey, Does it work on windows or is it better in a debian?

**Comment by MrDarkSkil** [comment]
it's better on Debian

**Comment by policeman18** [comment]
Okey, I have debian 8 I follow all the installation steps but, when I press the button "Finish Install" redirect me at the directory "finish_install" and when I click in "go to the login page" redirect me to mysql settings with all the tables saved except the server name

**Comment by policeman18** [comment]
Ps Sorry for my english and sorry for the inconvenience

**Comment by MrDarkSkil** [comment]
Press F5

**Comment by policeman18** [comment]
I do it, And I open the page in "private navigation"

**Comment by policeman18** [comment]
I got the launcher to work without the 404 error, but when I log I get a database error, where is in the configuration to put database and password?

**Comment by iWirk** [comment]
its in "configs/mysql_connect.php"
