### ISSUE TITLE
plus de guid au la création du compte 5.1 ?

### ISSUE THREAD

**Issue by bozoweed** [MrDarkSkil/Launcher_Multigaming#26]
salut salut mr darkskill vous navez pas garder le guid registration pour la 5.1 ? :o 
je peut le re rajouter si tu veut ;)

**Comment by MrDarkSkil** [comment]
Je travaille sur une nouvelle version qui sera plus rapide et plus sécurisé et plus personnalisable, donc si tu veux le fix temporairement va y 😉

**Comment by bozoweed** [comment]
Wo je vais attendre ta nouvelle version pour faire ça ^^

**Comment by MrDarkSkil** [comment]
OK 😄
