### ISSUE TITLE
The server is not accessible

### ISSUE THREAD

**Issue by cshard447** [MrDarkSkil/Launcher_Multigaming#27]
Help me please
my system
OC: Windows 7
Web Server:OpenServer(local server on my pc)
HTTP Module: Apache 2.4
PHP Module: PHP 5.6
MYSQL Module: Mysql 5.5
I installed the control panel and the setup apiurl
but when I run the launcher, writes to me "The server is not accessible"

Sorry for my bad english
![screenshot_4](https://cloud.githubusercontent.com/assets/7473900/22815746/49288aac-ef66-11e6-8ba1-1a980ceae5be.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/7473900/22815745/4927813e-ef66-11e6-9a3c-22c81793b34e.png)

**Comment by cshard447** [comment]
the problem is solved,sorry

**Comment by MrDarkSkil** [comment]
Si
