### ISSUE TITLE
Web Windows

### ISSUE THREAD

**Issue by FreezePirate** [MrDarkSkil/Launcher_Multigaming#35]
Hello, before i use debian 8 for your web-panel and it was fine. But now i have to use windows with some problems. I can't make update( always creating update), server status is waiting and doesn't change. Thank You !

**Comment by MrDarkSkil** [comment]
The server's status doesn't work on windows, i look how can i fix that.
You can't make update for what ? Launcher or Addons ?

**Comment by FreezePirate** [comment]
Addons update and server status.

**Comment by MrDarkSkil** [comment]
Ok so, when you click on "create an update" button what happens ?

**Comment by FreezePirate** [comment]
Creating update in progress, don\'t refresh this page ! 

And nothing... Just this message.

**Comment by MrDarkSkil** [comment]
Humm ... what is size of your mod pack ?

**Comment by FreezePirate** [comment]
9,37 GB , but before update takes about 10 min maximum 12. But now nothing happens

**Comment by MrDarkSkil** [comment]
Humm.. i don't know why. Can you give me your panel link ?
