### ISSUE TITLE
Test SQL doesn't work then installation can't be make

### ISSUE THREAD

**Issue by Tiiix** [MrDarkSkil/Launcher_Multigaming#37]
Hi there,

I try to install your webpanel on my Debian 8 server, but it doesn't works fine...
When I make all steps of the Wiki  : 
https://github.com/MrDarkSkil/Launcher_Multigaming/wiki/Intall-guide-for-DEBIAN-8-[FR]

Then, I try to connect on the IP adress of my server by Chrome for example, the form of connection information to mysql server appears, but, the SQL Test doesn't work, so, the installation can't be end.

How can I fix that ?

**Comment by AntoineVarla** [comment]
I have the same problem

**Comment by MrDarkSkil** [comment]
It's now fixed

**Comment by Tiiix** [comment]
@MrDarkSkil The problem persists, on the finish install this time. When the Mysql injection is made, the finish install does not succeed.. Nothing happen when I click on the "Finish install button".

I have this problem on 8 different servers, so I think it can be an oversight, a dependency or a problem of permissions :/
