### ISSUE TITLE
Add a call to "keys" directory

### ISSUE THREAD

**Issue by Tiiix** [MrDarkSkil/Launcher_Multigaming#41]
Hi, 
Is it possible to add a call to "modpack/keys" folder soon in order to use .bikey files, for signing Arma addons?

Thanks

**Comment by iWirk** [comment]
The .bkey files must be placed inside keys folder on the server not in the client 's addons.

**Comment by Tiiix** [comment]
@iWirk Hi, 
Nop, if the key is not on two sides, the client can't be authentificated by the server, so he can't access to server with the server_addons ;)

**Comment by iWirk** [comment]
Nop you are wrong on the client the .bisign are used the .bikey belongs on the server.

**Comment by MrDarkSkil** [comment]
Hi,
this problem is solved ? 
@Tiiix

**Comment by Tiiix** [comment]
Hi there, yeah it's okey @MrDarkSkil
