### ISSUE TITLE
soucis upload launcher

### ISSUE THREAD

**Issue by fredloy** [MrDarkSkil/Launcher_Multigaming#42]
bonjour je fais un appel car jai un souci pour upload le launcher sur le webpanel jai mis un dossier launcher dans /var/www/html/games ji ai mis la compile du launcher dedans mais sur le webpanel je narrive pas a lupload manuelement si besoin je pe donner lip du webpanel et autre

**Comment by FlashModz** [comment]
Salut @fredloy 
pourrai-tu nous dire si tu à bien crée le dossier pour le launcher, 
si celui-ci respecte bien les permission et si son groupe UNIX est bien en www-data ? 

Le cas échéant je t'invite à nous fournir des screens de ton FTP et en command line de nous fournir la réponse de cette commande : ls -l 

dans le dossier racine web du launcher.

FlashModz

**Comment by fredloy** [comment]
merci de vous etre penché sur mon probleme bravo pour le professionnalisme

**Comment by MrDarkSkil** [comment]
Bon j'ai fix le problème, merci pour ton retour @fredloy
