### ISSUE TITLE
CS0246 erreur !

### ISSUE THREAD

**Issue by KazeroG** [MrDarkSkil/Launcher_Multigaming#47]
**Erreur : CS0246**	
**Message :**	 Le nom de type ou d'espace de noms 'RestSharp' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?)	
**File :**	 C:\...\Launcher_Multigaming-5.0\LauncherArma3\LauncherArma3\serverChoose.cs	
**ligne :**	3	
**État :**	 Actif

**Erreur :** CS0246	
**Message :** Le nom de type ou d'espace de noms 'RestSharp' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?)	
**File :** C:\...\Launcher_Multigaming-5.0\LauncherArma3\LauncherArma3\loginForm.cs	
**ligne :** 5	
**État :** Actif

**Erreur :** CS0246	
**Message :** Le nom de type ou d'espace de noms 'RestSharp' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?)	
**File :** C:\...\Launcher_Multigaming-5.0\LauncherArma3\LauncherArma3\registerForm.cs
**ligne :** 2	
**État :** Actif

**Erreur :** CS0246	
**Message :** Le nom de type ou d'espace de noms 'RestSharp' est introuvable (vous manque-t-il une directive using ou une référence d'assembly ?)	
**File :** C:\...\Launcher_Multigaming-5.0\LauncherArma3\LauncherArma3\launcherMain.cs	
**ligne :** 8
**État :** Actif

**Comment by MrDarkSkil** [comment]
Tu as cette erreur lors de la compilation ?

**Comment by KazeroG** [comment]
oui ! exactement !

**Comment by MrDarkSkil** [comment]
D'accord, tu as changer des trucs pour que ça te fasse ça ?

**Comment by KazeroG** [comment]
les seule modification que jai fait cest celle énoncer dans le petit wiki ! cest a dire jai modifier a ma guise ces option: 

`/* GENERAL OPTIONS */

string communityName = "**IslandLife**";  /* Your serverName */
string apiUrl = "http://**ipdemonpanel**/"; /* Link to API launcher Arma 3 */

bool modDev = true; /* enable or disable modDev */`

**Comment by KazeroG** [comment]
@FlashModz cest a dire comment ? on ajoute une command `Install-Package RestSharp -Version 106.2.1` ? ou no ajoute manuellement des fichiers ?

merci pour ton aide !

**Comment by MrDarkSkil** [comment]
Avec NuGet directement, soit via la commande, soit via le gestionnaires NuGet visuel :) Comme tu veux

**Comment by MrDarkSkil** [comment]
Du coup tu peux avec cette commande :) 
```
Install-Package RestSharp -Version 106.2.1
```

**Comment by KazeroG** [comment]
@MrDarkSkil du coup je l'ajoute ou ?

**Comment by MrDarkSkil** [comment]
Pour ça il faut que tu créées un Installer 
Suis ce tuto 😃 https://github.com/MrDarkSkil/Launcher_Multigaming/wiki/Créer-un-installateur-du-launcher-%5BFR%5D

**Comment by KazeroG** [comment]
👍 💯 merci beaucoup ! et pardon du derengement !

**Comment by MrDarkSkil** [comment]
Il n'y a pas de quoi n'hésites pas si tu as d'autres problèmes et ne soit pas désolé 😉
