### ISSUE TITLE
Bug Js : Panel 

### ISSUE THREAD

**Issue by Mennajy** [MrDarkSkil/Launcher_Multigaming#48]
## Tell if it's a panel or launcher bug:
- [x] Panel bug
- [ ] Launcher bug

## Brief of your 

Salut, je n'arrive pas a aller plus loin que la page d'inscription sur l'installation du site web, la configuration de la bdd fonctionne mais je ne peut rien faire apres l'inscription. Le bouton s'enregistrer ne foncitonne pas
## Operating system
Xampp

## Logs
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
[En savoir plus]
localhost:140:39
finishInstall/</<
http://localhost/#:140:39
j
http://localhost/assets/js/jquery.min.js:2:27239
fireWith
http://localhost/assets/js/jquery.min.js:2:28057
x
http://localhost/assets/js/jquery.min.js:4:21841
b
http://localhost/assets/js/jquery.min.js:4:25897

**Comment by FlashModz** [comment]
Salut, pourrai-tu nous posté les LOGS suivants : 
- Apache
-  PHP

Pourrai-tu également nous communiqué ta configuration PHP & Apache ainsi que le type de SQL ?
Exemple : 

- PHP.INI
- HTTPD.CONF
- Un page avec ta config PHP complète
- Mysql / Sqlite / PostgreSql

utilise Pastebin ce sera plus sympa pour nous consulté tes logs.
Merci à toi :)

**Comment by Mennajy** [comment]
Salut,

Log Apache

https://pastebin.com/9VDQXTw6

La configuration est celle par défaut faite par xampp

**Comment by MrDarkSkil** [comment]
Peux tu venir discord ? https://discord.gg/8xMvep

**Comment by Mennajy** [comment]
J'y suis

**Comment by FlashModz** [comment]
@Mennajy il me faudrai tes logs d'erreur PHP aussi :)

**Comment by FlashModz** [comment]
Problème avec le fichier Config OLD / New du au fait qu'il ne retourne pas un tableau après ce bout de code server_name : document.getElementById("server_name").value
Située ligne : 154.

Voir avec @iWirk à son retour et je vais bossé sur la question en attendant.

**Comment by FlashModz** [comment]
Aucune réponse depuis, nous supposons que le soucis à été résolu,
dans le cas inverse merci de ré-ouvrir le sujet
