### ISSUE TITLE
SQL test not funtioning; installation cant be done

### ISSUE THREAD

**Issue by WeizenBoss** [MrDarkSkil/Launcher_Multigaming#51]
## Tell if it's a panel or launcher bug:
- [X] Panel bug
- [ ] Launcher bug

## Brief of your bug
Hello,
I have unpacked the webpanel.zip and can open it, but if I entered the database access data unfortunately nothing happens, neither if I test the connection nor if I click on "finish install" after I have entered all admin access data.

It's the same problem as here: https://github.com/MrDarkSkil/Launcher_Multigaming/issues/37

## Operating system
Ubuntu (with Plesk)

## Logs
which one do you need?

**Comment by FlashModz** [comment]
Hello,

if possible for you to join Discord ?
Adress ==> https://discord.gg/5KmWmDn

**Comment by MrDarkSkil** [comment]
Can you try to reinstall the web panel?  
It's normally fixed.

If you have an error can you add a screen of your web browser console ?

**Comment by WeizenBoss** [comment]
I already tried to reinstall the panel, but still nothing happening.

The console has the following error: http://prntscr.com/j1fc68

**Comment by FlashModz** [comment]
OS Server ? ==> Please update to latest version.

**Comment by WeizenBoss** [comment]
The latest version is already installed. http://prntscr.com/j1poor

**Comment by WeizenBoss** [comment]
Maybe there is something missing? http://prntscr.com/j1qerj

**Comment by FlashModz** [comment]
Problems Fixed : 

Plesk use Number for identify your user and your domain.
Php 5.6.35 min ( your 5.5 ).
do not replace your user by www-data, error with plesk. ( try this )
And set manually config tree to 777.

Finally, problems due to Plesk, not Launcher
