### ISSUE TITLE
lot of redirection file error

### ISSUE THREAD

**Issue by KazeroG** [MrDarkSkil/Launcher_Multigaming#56]
## Tell if it's a panel or launcher bug:
- [X] Panel bug
- [ ] Launcher bug

## Brief of your bug
some file cant be found and are not well referenced (with direct or indirect link).
like js file or other even when  #55 is well  configured

## Operating system
linux/ubuntu

**Comment by MrDarkSkil** [comment]
Can you add some screenshot ? And logs ?

**Comment by MrDarkSkil** [comment]
Pas de réponses, je close l'issue.

N'hésite pas à la rouvrir pour expliquer ton problème.
