### ISSUE TITLE
Problème de création de serveur.

### ISSUE THREAD

**Issue by loann25310** [MrDarkSkil/Launcher_Multigaming#65]
## Tell if it's a panel or launcher bug:
- [X] Panel bug
- [ ] Launcher bug

## Brief of your bug
Impossible de créer un serveur.

## Operating system
Windows Serveur 2016 + Ampps 3.8

## Long description
Lors de la création d'un serveur sur le panel web une erreur apparaît et aucune entrée n’apparaît dans la base de données.

## Logs
https://imgur.com/a/BliaR7r

**Comment by MrDarkSkil** [comment]
Problème du mod de la bdd @FlashModz tu te rappelles d'ou ça venait ?

**Comment by FlashModz** [comment]
Salut,

Oui soucis liée au Mod BDD disponible et modifiable comme ceci : 

Edité le fichier mysqld.cnf qui ce trouve dans /etc/mysql/mysql.conf.d/
Ajouté sql_mode = ''
Sauvegarder et redémarrer votre service Mysql 👍 

Si cela ne résous pas le soucis n'hésitez pas à nous le communiqué.

Autre solution possible,

Le soucis proviens de votre User MySQL notamment du Root sur une version plus récente de Ampps, il vous suffirai de crée un nouvel utilisateur MySQL et de vous assurer qu'il est accessible 🥇

**Comment by FlashModz** [comment]
Mis à jour suite erreur

**Comment by loann25310** [comment]
Mais juste petit problème,
Je n'utilise pas le service MySQL de Ampps, mais celui de Wamp + un autre compte que root. Même après ajout de la ligne le problème persiste.
Faut il mettre à jour le site ?

**Comment by FlashModz** [comment]
Ok, pourquoi utilisez vous Wamp, est-ce possible pour vous d'utiliser uniquement ampps ?
Car des soucis de compatibilité nous ont déjà conduis à plusieurs problèmes avec Wamp.

**Comment by loann25310** [comment]
Non puisque à se que je me rappelle à moins qu'il y eu changement. Il est impossible d'hébergé plusieurs site avec votre api.

**Comment by loann25310** [comment]
Ce que je veux dire par là il est impossible d’adopter ce type d'architecture. Bien sure je sais qu'un serveur apache reste un serveur apache.
![Architecture](https://i.imgur.com/s8izM65.png)

**Comment by FlashModz** [comment]
Bonjour, il est entièrement possible d'adapter ce type d'architecture et j'irai même plus loin en vous disant que vous pouvant tout à fait avoir des répertoire web dans vos Documents.

Malheureusement,

Je serai dans l'impossibilité de vous aider avec Wamp et ce après avoir chercher pendant plusieurs heure ce qui posait problème. Wamp à visiblement un soucis d'architecture de cryptage que nous ne pouvons résoudre sans l'aide de Wamp Directement qui à jusqu'ici désirée ne pas répondre à mes demandes vis à vis de ce problème.
