### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SergioDeoxGames** [MrDarkSkil/Launcher_Multigaming#68]
## Tell if it's a panel or launcher bug:
- [X] Panel bug
- [ ] Launcher bug

## Brief of your bug
![image](https://user-images.githubusercontent.com/32938058/51431326-9fb12600-1c27-11e9-84c5-96783f4e59a4.png)

**Comment by MrDarkSkil** [comment]
Can you tell me how i can reproduce this bug ?

**Comment by SergioDeoxGames** [comment]
I'm using Ubuntu Linux 18.10

**Comment by SergioDeoxGames** [comment]
Some files doesn't exists like: configs/config_mysql.php

**Comment by SergioDeoxGames** [comment]
Can we talk in discord?

**Comment by FlashModz** [comment]
Please follow the wiki and install webpanel on debian 9,x ;)

**Comment by SergioDeoxGames** [comment]
I dont have debian :(

**Comment by FlashModz** [comment]
Ok, but actualy only for Debian ... if you want to keep your Ubuntu can you solve this problem autonomously. for this type of service contact us on Discord (Service Paying by the hour)

**Comment by SergioDeoxGames** [comment]
What is your discord

**Comment by FlashModz** [comment]
https://discord.gg/75pQdYx

**Comment by FlashModz** [comment]
Error due to use Ubuntu, Issue Closed
